'use client'
import { FormEvent, useEffect, useState } from 'react'
import type { ResourceConfig } from '@/lib/admin-resources'

export function AdminResourceManager({resource,config}:{resource:string;config:ResourceConfig}){
 const [rows,setRows]=useState<any[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 async function load(){const r=await fetch(`/api/admin/${resource}`);const j=await r.json();if(r.ok)setRows(j.data||[]);else setError(j.error||'Unable to load')}
 useEffect(()=>{load()},[resource])
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget);const body:any={};config.fields.forEach(f=>{if(f.type==='checkbox')body[f.name]=fd.get(f.name)==='on';else if(f.type==='number'&&fd.get(f.name)!=='')body[f.name]=Number(fd.get(f.name));else if(fd.get(f.name)!=='')body[f.name]=fd.get(f.name)});try{const r=await fetch(`/api/admin/${resource}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Create failed');(e.currentTarget as HTMLFormElement).reset();await load()}catch(e){setError(e instanceof Error?e.message:'Create failed')}finally{setBusy(false)}}
 async function edit(row:any){const id=row.id??row.key;if(!id)return;const patch:any={};for(const f of config.fields){if(f.type==='checkbox'){if(confirm(`Toggle ${f.label}? Current: ${Boolean(row[f.name])}`))patch[f.name]=!row[f.name]}else{const value=prompt(`${f.label}`,row[f.name]??'');if(value!==null&&String(value)!==String(row[f.name]??''))patch[f.name]=f.type==='number'&&value!==''?Number(value):value}}if(!Object.keys(patch).length)return;const r=await fetch(`/api/admin/${resource}?id=${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});const j=await r.json();if(!r.ok)setError(j.error||'Update failed');else load()}
 async function remove(row:any){const id=row.id??row.key;if(!id||!confirm('Delete/archive this record?'))return;const r=await fetch(`/api/admin/${resource}?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(r.ok)load();else{const j=await r.json();setError(j.error||'Delete failed')}}
 return <><div className="pageHead"><div><h1>{config.title}</h1><p>{config.description}</p></div></div>{config.fields.length>0&&resource!=='students'&&resource!=='certificates'&&resource!=='reviews'&&<form className="adminForm" onSubmit={create}>{config.fields.map(f=><label key={f.name}>{f.label}{f.type==='textarea'?<textarea name={f.name} required={f.required}/>:f.type==='select'?<select name={f.name} required={f.required}><option value="">Select</option>{f.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>:f.type==='checkbox'?<input name={f.name} type="checkbox"/>:<input name={f.name} type={f.type||'text'} required={f.required}/>}</label>)}<button className="btn btnGold" disabled={busy}>{busy?'Saving…':'Add Record'}</button></form>}{error&&<div className="notice">{error}</div>}<div className="tableWrap"><table><thead><tr><th>ID</th>{config.fields.slice(0,5).map(f=><th key={f.name}>{f.label}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id??row.key}><td className="mono">{String(row.id??row.key).slice(0,16)}</td>{config.fields.slice(0,5).map(f=><td key={f.name}>{typeof row[f.name]==='object'?JSON.stringify(row[f.name]):String(row[f.name]??'')}</td>)}<td>{config.fields.length>0&&<button className="linkBtn" style={{color:'#0a55ba',marginRight:10}} onClick={()=>edit(row)}>Edit</button>}{!['students','payments','certificates','orders','enrollments'].includes(resource)&&<button className="linkBtn" onClick={()=>remove(row)}>Delete</button>}</td></tr>)}</tbody></table></div></>
}
