export type Field = { name:string; label:string; type?:'text'|'number'|'date'|'datetime-local'|'checkbox'|'textarea'|'select'; options?:string[]; required?:boolean }
export type ResourceConfig = { table:string; title:string; description:string; fields:Field[] }

export const ADMIN_RESOURCES: Record<string, ResourceConfig> = {
  courses: { table:'courses', title:'Courses', description:'Create, price, publish and manage courses.', fields:[
    {name:'title',label:'Title',required:true},{name:'slug',label:'Slug',required:true},{name:'category',label:'Category',type:'select',options:['Maths','English','Combo','Live Batch'],required:true},{name:'short_description',label:'Short Description',type:'textarea'},{name:'description',label:'Description',type:'textarea'},{name:'price_paise',label:'Price (paise)',type:'number',required:true},{name:'discount_price_paise',label:'Discount Price (paise)',type:'number'},{name:'level',label:'Level'},{name:'language',label:'Language'},{name:'duration_text',label:'Duration'},{name:'thumbnail_path',label:'Thumbnail Storage Path'},{name:'live_class_enabled',label:'Weekly Live Classes',type:'checkbox'},{name:'certificate_enabled',label:'Certificate Enabled',type:'checkbox'},{name:'published',label:'Published',type:'checkbox'} ] },
  modules: { table:'course_modules', title:'Modules', description:'Organize lessons into ordered course modules.', fields:[{name:'course_id',label:'Course UUID',required:true},{name:'title',label:'Module Title',required:true},{name:'position',label:'Position',type:'number'}] },
  lessons: { table:'lessons', title:'Lessons', description:'Manage videos, text lessons, previews and completion settings.', fields:[{name:'module_id',label:'Module UUID',required:true},{name:'title',label:'Lesson Title',required:true},{name:'lesson_type',label:'Type',type:'select',options:['video','text','quiz'],required:true},{name:'video_provider',label:'Video Provider'},{name:'video_asset_id',label:'Private Video Asset ID'},{name:'duration_seconds',label:'Duration Seconds',type:'number'},{name:'position',label:'Position',type:'number'},{name:'is_preview',label:'Free Preview',type:'checkbox'},{name:'published',label:'Published',type:'checkbox'}] },
  students: { table:'profiles', title:'Students', description:'View and update platform users. Role changes are sensitive and audited.', fields:[{name:'full_name',label:'Full Name'},{name:'phone',label:'Phone'},{name:'role',label:'Role',type:'select',options:['student','instructor','admin','super_admin']}] },
  quizzes: { table:'quizzes', title:'Quizzes', description:'Create course quizzes and configure passing/completion requirements.', fields:[{name:'course_id',label:'Course UUID',required:true},{name:'lesson_id',label:'Lesson UUID'},{name:'title',label:'Quiz Title',required:true},{name:'passing_percent',label:'Passing %',type:'number'},{name:'required_for_completion',label:'Required for Completion',type:'checkbox'}] },
  resources: { table:'lesson_resources', title:'Study Materials', description:'Attach private PDFs and learning resources to lessons.', fields:[{name:'lesson_id',label:'Lesson UUID',required:true},{name:'title',label:'Title',required:true},{name:'resource_type',label:'Type',type:'select',options:['pdf','link','worksheet']},{name:'storage_path',label:'Private Storage Path'},{name:'url',label:'External URL'}] },
  orders: { table:'orders', title:'Orders', description:'Review checkout orders and payment state.', fields:[] },
  enrollments: { table:'enrollments', title:'Enrollments', description:'Review active, completed and revoked course access.', fields:[] },
  reviews: { table:'reviews', title:'Reviews', description:'Moderate submitted student reviews.', fields:[{name:'status',label:'Status',type:'select',options:['pending','approved','rejected']}] },
  payments: { table:'payments', title:'Payments', description:'Review gateway transactions. Payment status should normally be webhook-controlled.', fields:[] },
  'live-classes': { table:'live_classes', title:'Live Classes', description:'Schedule course live classes and add recordings afterwards.', fields:[{name:'course_id',label:'Course UUID',required:true},{name:'title',label:'Title',required:true},{name:'starts_at',label:'Date & Time',type:'datetime-local',required:true},{name:'duration_minutes',label:'Duration Minutes',type:'number'},{name:'teacher_name',label:'Teacher'},{name:'description',label:'Description',type:'textarea'},{name:'meeting_url',label:'Meeting URL'},{name:'recording_url',label:'Recording URL'},{name:'status',label:'Status',type:'select',options:['scheduled','live','completed','cancelled']}] },
  certificates: { table:'certificates', title:'Certificates', description:'View and revoke issued certificates.', fields:[{name:'revoked',label:'Revoked',type:'checkbox'}] },
  coupons: { table:'coupons', title:'Coupons', description:'Create percentage or flat discounts with limits.', fields:[{name:'code',label:'Code',required:true},{name:'discount_type',label:'Discount Type',type:'select',options:['percent','flat'],required:true},{name:'discount_value',label:'Discount Value',type:'number',required:true},{name:'minimum_order_paise',label:'Minimum Order (paise)',type:'number'},{name:'maximum_discount_paise',label:'Maximum Discount (paise)',type:'number'},{name:'starts_at',label:'Start',type:'datetime-local'},{name:'expires_at',label:'Expiry',type:'datetime-local'},{name:'usage_limit',label:'Usage Limit',type:'number'},{name:'per_user_limit',label:'Per User Limit',type:'number'},{name:'active',label:'Active',type:'checkbox'}] },
  settings: { table:'platform_settings', title:'Platform Settings', description:'Centralized brand, contact, tax, social and SEO configuration.', fields:[{name:'key',label:'Setting Key',required:true},{name:'value',label:'JSON Value',type:'textarea',required:true}] }
}
